name: XgpEquipmentSlot
version: ${project.version}
main: cn.xgpjun.xgpequipmentslot.XgpEquipmentSlot
api-version: '1.13'
authors: [1badsobig]

softdepend:
  - SX-Attribute
  - AttributePlus
  - ZF-Runes
  - PlaceholderAPI

commands:
  XgpEquipmentSlot:
    aliases:
      - xes
permissions:
  XgpES.bypass:
    default: op