name: "测试套装"
decision:
  lore: "测试套装"
  type: "test"
  regex: ".*?测试.*?套装.*"
bonus:
  potion:
    2:
      - "SPEED:1"
      - "LUCK:2"
  attribute:
    2:
      - "攻击力: 10"
      - "生命上限: 100"
    4:
      - "攻击力: 25"
      - "生命上限: 250"
      - "暴击几率: 1"
lore:
  name:
    - "&l&6&m      ❀&e测试套装{n}/4&6❀&m      "
  active:
    2:
      - "&a(2)套装: +10攻击力。"
      - "&a(2)套装: +100生命力。"
    4:
      - "&a(4)套装: +25攻击力。"
      - "&a(4)套装: +250生命力。"
      - "&a(4)套装: +1%暴击几率。"
      - "&l&6&m      ❀&e 套装信息 &6❀&m       "
  inactive:
    2:
      - "&7(2)套装: +10攻击力。"
      - "&7(2)套装: +100生命力。"
    4:
      - "&7(4)套装: +25攻击力。"
      - "&7(4)套装: +250生命力。"
      - "&7(4)套装: +1%暴击几率。"
      - "&l&6&m      ❀&e 套装信息 &6❀&m       "